#!/usr/bin/env python3
"""Draft the per-tool `**Tags**:` lines for review, from evidence in the docs themselves.

Hand-writing ~76 tag lines invites a hasty pass, and a wrong tag is worse than no tag: it turns
an honest miss into a confident wrong answer. This produces a reviewable draft instead — each
proposed tag with the line that justifies it, and the weak matches listed separately so they can
be struck rather than hunted for.

ACTION and SUBJECT are seeded from the category the docs already assign; CAPABILITY and READOUT
come from keyword evidence, which is where the truncated index blurb loses information.

Run from the repo root:  python skills/biopipelines/draft_tool_tags.py
"""

import io
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent.parent))

from biopipelines import tool_docs, tool_tags  # noqa: E402

OUT = (pathlib.Path(__file__).resolve().parent.parent.parent
       / "outputs" / "_views" / "tool_tags_draft.md")


def draft_for(entry):
    section = tool_docs.section(entry["name"]) or ""
    action, subject = tool_tags.seed_from_category(entry["category"])
    strong, weak = tool_tags.propose(section)

    facets = {"action": list(action), "subject": list(subject), "readout": [], "capability": []}
    for tag in strong:
        for facet, members in tool_tags.VOCABULARY.items():
            if tag in members and tag not in facets[facet]:
                facets[facet].append(tag)
    return facets, strong, weak, tool_tags.evidence(section)


def main():
    entries = tool_docs.collect()
    aliases = tool_tags.TAG_ALIAS

    lines = [
        "# Tool tags — draft for review",
        "",
        f"Generated by `skills/biopipelines/draft_tool_tags.py` from the docs themselves. "
        f"{len(entries)} tools. **Nothing has been written into `docs/tool/*.md`.**",
        "",
        "For each tool: the proposed `**Tags**:` line, then the evidence. `weak` matches are "
        "keywords found only in prose or an example — often a caveat about what the tool does "
        "*not* do, so read those before keeping them.",
        "",
        "ACTION and SUBJECT are seeded from the tool's category and will frequently be wrong for "
        "tools that do two things; CAPABILITY and READOUT are evidence-driven and are the facets "
        "the index blurb currently loses.",
        "",
        "Strike what is wrong, add what is missing, then hand it back.",
        "",
    ]

    by_cat = {}
    for entry in entries:
        by_cat.setdefault(entry["category"], []).append(entry)

    for category in sorted(by_cat):
        lines.append(f"## {category}")
        lines.append("")
        for entry in sorted(by_cat[category], key=lambda e: e["name"]):
            name = entry["name"]
            if name in aliases:
                lines.append(f"### {name}")
                lines.append("")
                lines.append(f"Shares `{aliases[name]}`'s implementation — same tags, "
                             f"kept in step by `TAG_ALIAS`.")
                lines.append("")
                continue

            facets, strong, weak, ev = draft_for(entry)
            proposed = [t for facet in tool_tags.FACETS for t in facets[facet]]

            lines.append(f"### {name}")
            lines.append("")
            lines.append(f"**Tags**: {', '.join(proposed) if proposed else '(none proposed)'}")
            lines.append("")
            for facet in tool_tags.FACETS:
                if facets[facet]:
                    source = "from category" if facet in ("action", "subject") else "from evidence"
                    lines.append(f"- *{facet}* ({source}): {', '.join(facets[facet])}")
            if weak:
                lines.append(f"- *weak, check before keeping*: {', '.join(weak)}")
            lines.append("")
            shown = [t for t in strong + weak
                     if t in tool_tags.VOCABULARY["capability"]
                     or t in tool_tags.VOCABULARY["readout"]]
            for tag in shown:
                zone, weight, excerpt = ev[tag][0]
                mark = "strong" if weight >= tool_tags.STRONG else "weak"
                lines.append(f"  - `{tag}` [{mark}, {zone}] {excerpt}")
            lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    io.open(OUT, "w", encoding="utf-8").write("\n".join(lines))
    tagged = sum(1 for e in entries if e["name"] not in aliases)
    print(f"{tagged} tools drafted -> {OUT.relative_to(OUT.parents[2])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
