"""
This pipeline shows how improve the difference in predicted binding affinity between open and close form of a carbocyanine 7 chloride and halotag7 starting from a Boltz model of the open form.
"""

import os, sys
sys.path.insert(0, os.getcwd()) #to see scripts in current folder

from PipelineScripts.pipeline import *
from PipelineScripts.load_output import LoadOutput
from PipelineScripts.ligand_mpnn import LigandMPNN
from PipelineScripts.mutation_profiler import MutationProfiler
from PipelineScripts.mutation_composer import MutationComposer
from PipelineScripts.mmseqs2 import MMseqs2
from PipelineScripts.boltz2 import Boltz2
from PipelineScripts.residue_atom_distance import ResidueAtomDistance
from PipelineScripts.merge_datasheets import MergeDatasheets
from PipelineScripts.concatenate_datasheets import ConcatenateDatasheets
from PipelineScripts.remove_duplicates import RemoveDuplicates
from PipelineScripts.filter import Filter
from PipelineScripts.select_best import SelectBest
from PipelineScripts.average_by_datasheet import AverageByDatasheet
from PipelineScripts.extract_metrics import ExtractMetrics

with Pipeline(project="Examples",
              job="LigandMPNN-MutationComposer-MMseqs-Cycle",
              description="Profiling of mutations occuring over 1000 sequences generated by LigandMPNN and composition of sequences based on it, cycling to improve difference in affinity between open and bound"):

    Resources(gpu="A100",
              time="23:59:00",
              memory="16GB")

    original_open = LoadOutput('/shares/locbp.chem.uzh/public/BioPipelines/Boltz/HT7_Cy7_C_R_001/ToolOutputs/1_Boltz2_output.json')
    original_close = LoadOutput('/shares/locbp.chem.uzh/public/BioPipelines/Boltz/HT7_Cy7_C_RR_001/ToolOutputs/1_Boltz2_output.json')

    best_open,best_close=original_open,original_close

    original_analysis = MergeDatasheets(datasheets=[best_open.datasheets.affinity,
                                                    best_close.datasheets.affinity],
                                        prefixes=["open_", "close_"],
                                        id_map={"original":["HT7_Cy7_C_R","HT7_Cy7_C_RR"]},
                                        calculate={"affinity_delta": "open_affinity_pred_value - close_affinity_pred_value"})

    NUM_CYCLES = 20
    all_sequences_seen = None  # Track all sequences across cycles

    # Track all analyses and pools across cycles for SelectBest
    all_analyses = [original_analysis]  # Start with original baseline
    all_pools = [best_open]  # Start with original best structure

    for CYCLE in range(NUM_CYCLES):
        Suffix(f"Cycle{CYCLE+1}")

        mutation_range = "141+143+145+147-149+151-152+154+157+160-161+165+167-168+170-172+175-176+178+180+245+271"
        lmpnn = LigandMPNN(structures=best_open, #this is equivalent to boltz2
                            ligand="LIG", #in ligand mpnn you should always specify the ligand name, which is LIG if from Boltz
                            num_sequences=1000,
                            batch_size=25, 
                            redesigned=mutation_range, #similarly you can specify fixed=...
                            design_within=4)
        
        profiler = MutationProfiler(original=best_open,
                                    mutants=lmpnn)
        composer = MutationComposer(frequencies=profiler.datasheets.absolute_frequencies,
                                    num_sequences=20,
                                    mode="weighted_random",
                                    max_mutations=3)
        
        #Update history with unique sequences after deduplication
        unique_new_sequences = RemoveDuplicates(pool=composer,           # Current cycle sequences  
                                                history=all_sequences_seen if all_sequences_seen else None,  # History from previous cycles (None for first cycle)
                                                compare="sequence")           # Compare protein sequences

        if all_sequences_seen is None:
            # First cycle - initialize history with ConcatenateDatasheets (single input)
            all_sequences_seen = ConcatenateDatasheets(datasheets=[unique_new_sequences.datasheets.sequences])
        else:
            # Subsequent cycles - concatenate unique sequences with existing history
            all_sequences_seen = ConcatenateDatasheets(datasheets=[unique_new_sequences.datasheets.sequences, 
                                                                   all_sequences_seen.datasheets.concatenated])
        
        msas = MMseqs2(sequences=unique_new_sequences)
        boltz_holo_open = Boltz2(proteins=unique_new_sequences,
                                ligands=original_open,
                                msas=msas,
                                affinity=True)
        boltz_holo_close = Boltz2(proteins=unique_new_sequences,
                                ligands=original_close,
                                msas=msas,
                                affinity=True)
        
        open_chlorine_aspartate_distance = ResidueAtomDistance(structures=boltz_holo_open,
                                                                residue='D in IHDWG',
                                                                atom='LIG.Cl',
                                                                metric_name='open_chlorine_distance')
        open_cap_aspartate_distance = ResidueAtomDistance(structures=boltz_holo_open,
                                                            residue='D in IHDWG',
                                                            atom='LIG.N88',
                                                            metric_name='open_cap_distance')
        current_analysis = MergeDatasheets(datasheets=[boltz_holo_open.datasheets.affinity,
                                                        boltz_holo_close.datasheets.affinity,
                                                        open_chlorine_aspartate_distance.datasheets.analysis,
                                                        open_cap_aspartate_distance.datasheets.analysis],
                                            prefixes=["open_","close_","",""],
                                            calculate = {"affinity_delta":"open_affinity_pred_value-close_affinity_pred_value"} )
        current_filtered = Filter(data=current_analysis,
                                    expression="open_chlorine_distance < 5.0 and open_cap_distance > 10.0")
        
        # Add current cycle results to the arrays
        all_pools.append(boltz_holo_open)
        all_analyses.append(current_filtered)
        
        best_open = SelectBest(pool=[pool for pool in all_pools],  # We select the best across all cycles
                               datasheets=[x.datasheets.merged for x in all_analyses],  # All analyses from all cycles
                               metric='open_affinity_pred_value',
                               mode='min',
                               name=f'{CYCLE+1}_best')

    all_merged = [x.datasheets.merged for x in all_analyses]
    combined_datasheets = ConcatenateDatasheets(all_merged)
    AverageByDatasheet(all_merged)

    #extract metrics for column analysis on Prism
    metrics = ["affinity_delta",
            "open_affinity_pred_value",
            "close_affinity_pred_value"]
    ExtractMetrics(datasheets=all_merged,
                    metrics=metrics)

