"""
This pipeline shows how to generate a lot of LigandMPNN sequences,
use MutationProfiler to identify which mutations have been generated across all 1000 sequences,
and use several modes of the MutationComposer to generate new sequences and fold them with Boltz2.

We also fold the first 10 sequences generated by LigandMPNN for comparison with the ones generated by MutationComposer.
"""

import os, sys
sys.path.insert(0, os.getcwd()) #to see scripts in current folder

from PipelineScripts.pipeline import Pipeline
from PipelineScripts.load_output import LoadOutput
from PipelineScripts.ligand_mpnn import LigandMPNN
from PipelineScripts.slice_datasheet import SliceDatasheet
from PipelineScripts.boltz2 import Boltz2
from PipelineScripts.residue_atom_distance import ResidueAtomDistance
from PipelineScripts.merge_datasheets import MergeDatasheets
from PipelineScripts.mutation_profiler import MutationProfiler
from PipelineScripts.mutation_composer import MutationComposer
from PipelineScripts.filter import Filter
from PipelineScripts.concatenate_datasheets import ConcatenateDatasheets
from PipelineScripts.extract_metrics import ExtractMetrics


pipeline = Pipeline(
    pipeline_name="LigandMPNN-MutationComposer", #Will create a folder in /shares/USER/<pipeline_name>
    job_name="HT7_Cy7_C_R", #Unique job folder in /shares/USER/<pipeline_name>/job_name_NNN
    job_description="Profiling of mutations occuring over 1000 sequences generated by LigandMPNN, with first 10 sequences folded for comparison")

pipeline.resources(
    gpu="V100",
    time="24:00:00",
    memory="16GB"
)


original_open = pipeline.add(LoadOutput('/shares/locbp.chem.uzh/public/BioPipelines/Boltz/HT7_Cy7_C_R_001/ToolOutputs/1_Boltz2_output.json'))
original_close = pipeline.add(LoadOutput('/shares/locbp.chem.uzh/public/BioPipelines/Boltz/HT7_Cy7_C_RR_001/ToolOutputs/1_Boltz2_output.json'))

original_analysis = pipeline.add(MergeDatasheets(datasheets=[original_open.datasheets.affinity,
                                                             original_close.datasheets.affinity],
                                                prefixes=["open_","close_"],
                                                id_map={'original':["HT7_Cy7_C_R","HT7_Cy7_C_RR"]}),
                                                calculate = {"affinity_delta":"open_affinity_pred_value-close_affinity_pred_value"})

mutation_range = "141+143+145+147-149+151-152+154+157+160-161+165+167-168+170-172+175-176+178+180+245+271"
lmpnn = pipeline.add(LigandMPNN(structures=original_open, #this is equivalent to boltz2
                                ligand="LIG",
                                num_sequences=1000,
                                batch_size=25,
                                redesigned=mutation_range,
                                design_within=4))


pipeline.set_suffix("first_10") #suffix for these tools
first_10_sequences = pipeline.add(SliceDatasheet(
    input=lmpnn,
    n_rows=10
))


#Fold the first 10 sequences from LigandMPNN for comparison
boltz_apo_first10 = pipeline.add(Boltz2(proteins=first_10_sequences))
boltz_holo_open_first10 = pipeline.add(Boltz2(proteins=first_10_sequences,
                                ligands=original_open,
                                msas=boltz_apo_first10,
                                affinity=True))
boltz_holo_close_first10 = pipeline.add(Boltz2(proteins=first_10_sequences,
                                ligands=original_close,
                                msas=boltz_apo_first10,
                                affinity=True))
open_chlorine_aspartate_distance_first10 = pipeline.add(ResidueAtomDistance(input=boltz_holo_open_first10,
                                                                    residue='D in IHDWG',
                                                                    atom='LIG.Cl',
                                                                    metric_name='open_chlorine_distance'))
close_chlorine_aspartate_distance_first10 = pipeline.add(ResidueAtomDistance(input=boltz_holo_close_first10,
                                                                    residue='D in IHDWG',
                                                                    atom='LIG.Cl',
                                                                    metric_name='close_chlorine_distance'))
analysis_first10 = pipeline.add(MergeDatasheets(datasheets=[boltz_holo_open_first10.datasheets.affinity,
                                                    boltz_holo_close_first10.datasheets.affinity,
                                                    open_chlorine_aspartate_distance_first10.datasheets.analysis,
                                                    close_chlorine_aspartate_distance_first10.datasheets.analysis],
                                        prefixes=["open_","close_","",""],
                                        calculate = {"affinity_delta":"open_affinity_pred_value-close_affinity_pred_value"} ))


pipeline.set_suffix("") #remove suffix
profiler = pipeline.add(MutationProfiler(original=original_open,
                        mutants=lmpnn))

all_analysis=[original_analysis,analysis_first10]  # Include first 10 analysis

for mode in ["single_point","weighted_random","hotspot_focused","top_mutations"]:
    pipeline.set_suffix(mode) #all folders generated from now on will have this suffix
    composer = pipeline.add(MutationComposer(frequencies=profiler.datasheets.absolute_frequencies,
                                            num_sequences=10,
                                            mode=mode,
                                            prefix=mode))

    boltz_apo = pipeline.add(Boltz2(proteins=composer))
    boltz_holo_open = pipeline.add(Boltz2(proteins=composer,
                                    ligands=original_open,
                                    msas=boltz_apo,
                                    affinity=True))
    boltz_holo_close = pipeline.add(Boltz2(proteins=composer,
                                    ligands=original_close,
                                    msas=boltz_apo,
                                    affinity=True))
    open_chlorine_aspartate_distance = pipeline.add(ResidueAtomDistance(input=boltz_holo_open,
                                                                        residue='D in IHDWG',
                                                                        atom='LIG.Cl',
                                                                        metric_name='open_chlorine_distance'))
    close_chlorine_aspartate_distance = pipeline.add(ResidueAtomDistance(input=boltz_holo_close,
                                                                        residue='D in IHDWG',
                                                                        atom='LIG.Cl',
                                                                        metric_name='close_chlorine_distance'))
    analysis = pipeline.add(MergeDatasheets(datasheets=[boltz_holo_open.datasheets.affinity,
                                                        boltz_holo_close.datasheets.affinity,
                                                        open_chlorine_aspartate_distance.datasheets.analysis,
                                                        close_chlorine_aspartate_distance.datasheets.analysis],
                                            prefixes=["open_","close_","",""],
                                            calculate = {"affinity_delta":"open_affinity_pred_value-close_affinity_pred_value"} ))
    filtered_analysis = pipeline.add(Filter(data=analysis,
                                 expression="open_chlorine_distance<5.0"))
    all_analysis.append(filtered_analysis)

pipeline.set_suffix("ALL_ANALYSIS")
pipeline.add(ConcatenateDatasheets([x.datasheets.merged for x in all_analysis]))
pipeline.add(ExtractMetrics(datasheets=[x.datasheets.merged for x in all_analysis],
                            metrics=["affinity_delta",
                                    "open_affinity_pred_value",
                                    "close_affinity_pred_value"]))

#Prints
pipeline.save()
pipeline.slurm()