"""
This pipeline shows how to generate a lot of LigandMPNN, use MutationProfiler to identify which mutations have been generated, and use several modes of the MutationComposer to generate new sequences and fold them with Boltz2
"""

#!/usr/bin/env python3
import os, sys
sys.path.insert(0, os.getcwd()) #to see scripts in current folder

from PipelineScripts.pipeline import Pipeline
from PipelineScripts.load_output import LoadOutput
from PipelineScripts.ligand_mpnn import LigandMPNN
from PipelineScripts.boltz2 import Boltz2
from PipelineScripts.residue_atom_distance import ResidueAtomDistance
from PipelineScripts.merge_datasheets import MergeDatasheets
from PipelineScripts.mutation_profiler import MutationProfiler
from PipelineScripts.mutation_composer import MutationComposer
from PipelineScripts.concatenate_datasheets import ConcatenateDatasheets
from PipelineScripts.filter import Filter

pipeline = Pipeline(
    pipeline_name="LigandMPNN-MutationComposer", #Will create a folder in /shares/USER/<pipeline_name>
    job_name="HT7_Cy7_C_R", #Unique job folder in /shares/USER/<pipeline_name>/job_name_NNN
    job_description="Profiling of mutations occuring over 1000 sequences generated by LigandMPNN and composition of sequences based on it")

pipeline.resources(
    gpu="V100",
    time="24:00:00",
    memory="16GB"
)

"""
It is best practise to start from a Boltz2 output with the open form, to have a benchmark affinity.
One can then load it with the LoadOutput tool, which will contain the same structures (pdbs), ids, and datasheets as the Boltz2 tool of the past pipeline.  
"""
original = pipeline.add(LoadOutput(
    '/shares/locbp.chem.uzh/gquarg/BioPipelines/Boltz/HT_Cy7_C_R_001/ToolOutputs/1_Boltz2_output.json'
    #'path/to/job/ToolOutputs/<Job>_Boltz2_output.json'
))

"""
Diversify with LigandMPNN
"""
lmpnn = pipeline.add(LigandMPNN(structures=original.output, #this is equivalent to boltz2.output
                                ligand="LIG", 
                                num_sequences=1000, 
                                batch_size=25,
                                redesigned="145-180", 
                                design_within=4))


profiler = pipeline.add(MutationProfiler(original=original.output,
                        mutants=lmpnn.output))

all_analysis=[]

for mode in ["single_point","weighted_random","hotspot_focused","top_mutations"]:
    pipeline.set_suffix(mode) #all folders generated from now on will have this suffix
    composer = pipeline.add(MutationComposer(frequencies=profiler.output.datasheets.absolute_frequencies,
                                            num_sequences=10,
                                            mode=mode,
                                            prefix=mode))

    """
    We run the Apo version first. One can also extract confidence parameters from it, and in general here is where we calculate the MSAs, which will be recycled later on with the msas input parameter.
    """
    boltz_apo = pipeline.add(Boltz2(proteins=composer.output))

    """
    Run with open form and closed form.
    Important: msas are passed with <tool>.output, not with <tool>.output.msas
    """
    boltz_holo_open = pipeline.add(Boltz2(proteins=composer.output,
                                    ligands=r"C[N+](C1=C2C=CC=C1)=C([C@]2(CC3=CN(N=N3)CCOCCOCCCCCCCl)CC(NCC(F)F)=O)/C=C/C=C/C=C/C=C(N(C4=C5C=CC=C4)C)\C5(C)C",
                                    msas=boltz_apo.output,
                                    affinity=True))
    boltz_holo_close = pipeline.add(Boltz2(proteins=composer.output,
                                    ligands=r"CN([C@@]1(/C=C/C=C/C=C/C=C(C2(C)C)/N(C)C3=C2C=CC=C3)[C@@]4(CC(N1CC(F)F)=O)CC5=CN(CCOCCOCCCCCCCl)N=N5)C6=C4C=CC=C6",
                                    msas=boltz_apo.output,
                                    affinity=True))
    open_chlorine_aspartate_distance = pipeline.add(ResidueAtomDistance(input=boltz_holo_open.output,
                                                                        residue='D in IHDWG',
                                                                        atom='LIG.Cl',
                                                                        metric_name='open_chlorine_distance'))
    close_chlorine_aspartate_distance = pipeline.add(ResidueAtomDistance(input=boltz_holo_close.output,
                                                                        residue='D in IHDWG',
                                                                        atom='LIG.Cl',
                                                                        metric_name='close_chlorine_distance'))
    analysis = pipeline.add(MergeDatasheets(datasheets=[boltz_holo_open.output.datasheets.affinity,
                                                        boltz_holo_close.output.datasheets.affinity,
                                                        open_chlorine_aspartate_distance.output.datasheets.analysis,
                                                        close_chlorine_aspartate_distance.output.datasheets.analysis],
                                            prefixes=["open_","close_","",""],
                                            calculate = {"affinity_delta":"open_affinity_pred_value-close_affinity_pred_value"} ))
    
    all_analysis.append(analysis)

combined_datasheets = pipeline.add(ConcatenateDatasheets([x.output.datasheets.merged for x in all_analysis]))

#Prints
pipeline.save()
pipeline.slurm(email="") 
