"""
This pipeline shows how to generate a lot of LigandMPNN and use MutationProfiler to analyze the results
"""

#!/usr/bin/env python3
import os, sys
sys.path.insert(0, os.getcwd()) #to see scripts in current folder

from PipelineScripts.pipeline import Pipeline
from PipelineScripts.load_output import LoadOutput
from PipelineScripts.ligand_mpnn import LigandMPNN
from PipelineScripts.mutation_profiler import MutationProfiler

pipeline = Pipeline(
    pipeline_name="LigandMPNN-MutationProfiler", #Will create a folder in /shares/USER/<pipeline_name>
    job_name="HT7_Cy7_C_R", #Unique job folder in /shares/USER/<pipeline_name>/job_name_NNN
    job_description="Profiling of mutations occuring over 1000 sequences generated by LigandMPNN")

pipeline.resources(
    gpu="V100",
    time="24:00:00",
    memory="16GB"
)

"""
It is best practise to start from a Boltz2 output with the open form, to have a benchmark affinity.
One can then load it with the LoadOutput tool, which will contain the same structures (pdbs), ids, and datasheets as the Boltz2 tool of the past pipeline.  
"""
original = pipeline.add(LoadOutput(
    '/shares/locbp.chem.uzh/gquarg/BioPipelines/Boltz/HT_Cy7_C_R_001/ToolOutputs/1_Boltz2_output.json'
    #'path/to/job/ToolOutputs/<Job>_Boltz2_output.json'
))

"""
Diversify with LigandMPNN
"""
lmpnn = pipeline.add(LigandMPNN(structures=original, #this is equivalent to boltz2
                                ligand="LIG", #in ligand mpnn you should always specify the ligand name, which is LIG if from Boltz
                                num_sequences=1000, 
                                batch_size=25, #1000 sequences will be split in 25 batches, 40 sequences each
                                redesigned="145-180", #similarly you can specify fixed=...
                                design_within=4))


"""
Profiler gives in output four datasheets:
  1. profile.csv - Position-wise mutation statistics
    - Columns: position, original, count, frequency
  2. mutations.csv - Raw amino acid mutation counts
    - Columns: position, original, <various amino acids>
    - Contains raw counts (integers) for each amino acid at each position
  3. absolute_frequencies.csv - Normalized frequencies (0.0-1.0)
    - Columns: position, original, <various amino acids>
    - Contains frequencies relative to total sequences
  4. relative_frequencies.csv - Mutation-relative frequencies (0.0-1.0)
    - Columns: position, original, <various amino acids>
    - Contains frequencies relative to mutations at each position
Plus some plots
"""
profiler = pipeline.add(MutationProfiler(original=original,
                        mutants=lmpnn))

#Prints
pipeline.save()
pipeline.slurm(email="") 
